Testing DbFindByDepartureAirportDay
Using sample DB from createSampleDb

Searching for flights from SYD on Monday
Found flights:
QF500|SYD|BNE|Monday 0400|30
QF409|SYD|MEL|Monday 0705|90
QF409|SYD|MEL|Monday 0800|90
QF530|SYD|BNE|Monday 1305|30

Searching for flights from SYD on Tuesday
Found flights:
QF500|SYD|BNE|Tuesday 0400|30
QF409|SYD|MEL|Tuesday 0705|90

Searching for flights from SYD on Wednesday
Found flights:
QF500|SYD|BNE|Wednesday 0400|30
QF409|SYD|MEL|Wednesday 0705|90
QF409|SYD|MEL|Wednesday 0800|90
QF530|SYD|BNE|Wednesday 1305|30

Searching for flights from SYD on Thursday
Found flights:
QF500|SYD|BNE|Thursday 0400|30
QF409|SYD|MEL|Thursday 0705|90
QF530|SYD|BNE|Thursday 1305|30

Searching for flights from SYD on Friday
Found flights:
QF500|SYD|BNE|Friday 0400|30
QF409|SYD|MEL|Friday 0705|90
QF530|SYD|BNE|Friday 1305|30

Searching for flights from SYD on Saturday
Found flights:
QF500|SYD|BNE|Saturday 0400|30
QF409|SYD|MEL|Saturday 0705|90
QF409|SYD|MEL|Saturday 0800|90

Searching for flights from SYD on Sunday
Found flights:
QF500|SYD|BNE|Sunday 0400|30
QF409|SYD|MEL|Sunday 0705|90
QF530|SYD|BNE|Sunday 1305|30

Searching for flights from ADL on Monday
Found flights:
JQ771|ADL|MEL|Monday 1405|105

Searching for flights from ADL on Tuesday
Found flights:
JQ771|ADL|MEL|Tuesday 1155|105
JQ771|ADL|MEL|Tuesday 1405|105

Searching for flights from ADL on Wednesday
Found flights:
JQ771|ADL|MEL|Wednesday 1405|105

Searching for flights from MEL on Thursday
Found flights:
JQ560|MEL|BNE|Thursday 0900|85
VA323|MEL|BNE|Thursday 1130|110

Searching for flights from MEL on Friday
Found flights:
JQ560|MEL|BNE|Friday 0900|85
VA323|MEL|BNE|Friday 1100|110

Searching for flights from MEL on Saturday
No flights found

Searching for flights from BNE on Monday
No flights found

Searching for flights from BNE on Tuesday
No flights found

Searching for flights from BNE on Wednesday
No flights found